name: Deploy HTML with OpenAI Key

on:
  push:
    branches:
      - main  # Trigger this workflow when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy HTML
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Deployment steps go here, for example:
          echo "Starting deployment..."
          # Here, use the API key if needed in a secure way
