env:
  EMAILJS_KEY: ${{ secrets.EMAILJS_KEY }}
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
  TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
